### ISSUE TITLE
Compare and contrast text for getting the SYSTEM_DOMAIN_NAME

### ISSUE THREAD

**Issue by pawsey-kbuckley** [Cray-HPE/docs-csm#2978]
Compare and contrast the text for getting the SYSTEM_DOMAIN_NAME
in these two sections of the manual:

operations/conman/Access_Console_Log_Data_Via_the_System_Monitoring_Framework_SMF.md

operations/system_management_health/Access_System_Management_Health_Services.md

In the former we read

```
Determine the external domain name by running the following command on any NCN:

kubectl get secret site-init -n loftsman -o jsonpath='{.data.customizations.yaml}' |
        base64 -d | grep "external:"
      external: SHASTA_EXTERNAL_DOMAIN.com
```

whilst in the latter, we read

```
The SYSTEM_DOMAIN_NAME value in the URLs on this page is an Ansible
variable that can be retrieved as follows. It is expected to be the
system’s fully qualified domain name (FQDN).

(ncn-mw#) This command can be run on any master or worker NCN.

kubectl get secret site-init -n loftsman -o jsonpath='{.data.customizations\.yaml}' | base64 -d | grep "external:"

Example output:

      external: SYSTEM_DOMAIN_NAME
```

The latter makes more sense, as it doesn't presume that
your site will be a dot-com, whilst the addition of that
dot-com in the former might have the uninitiated, and/or
naive, thinking that they have to add a dot-com to any
name that gets returned.

Probably worth taking the text from the latter and replacing
the text in the former with it, so as to be consistent.

FWIW, there's even a third way to do it presented in

 operations/package_repository_management/Restrict_Admin_Privileges_in_Nexus.md

but that's so different to the other two as to not cause confusion.

HTH

**Comment by rustydb** [comment]
@pawsey-kbuckley , thank you for the feedback. We'll look at getting these items into a consistent state.

**Comment by rustydb** [comment]
Fixed by https://github.com/Cray-HPE/docs-csm/pull/3864
