### ISSUE TITLE
Authoring of triple-backtick codblocks prevents rendering in Jekyll/Liquid

### ISSUE THREAD

**Issue by pawsey-kbuckley** [Cray-HPE/docs-csm#952]
There are a swathe of instances, throughout the source of these docs,
where "code blocks" are begun with the triple-backtick marker, but
are never closed with a corresponding one.

Whilst appreciating that you can "get away with it" in some rendering
environments, it's rather poor form, and,  more importantly,  it does 
break rendering in some envirtonments, with Jekyll/Liquid being the
one I have been trying to use locally.

Given that there are examples of code block markup where the author
has done the "right thing", it's clearly not some  "internal style guide 
authoring thing": more likely the result of an ad-hoc approach?

Any chance of fixing this up? 

Reason for not forking is that there is just too much of it to clean up!

**Comment by denniswalker** [comment]
Appreciate the feedback. We're looking into this now.

**Comment by gbaker-hpe** [comment]
Thanks for creating the issue and for the follow-up PRs.  This is a good change and can merge once the PRs are fixed up.

**Comment by pawsey-kbuckley** [comment]
Just following up on this, now the heat is off a bit here.

I gave up trying to re-base and just cloned the latest main branch
and have just pulled it up to date, so as to be at commit

```
3098cced5a0 (upstream/main, upstream/HEAD, main) CASMINST-4695: More linting
```

The good news:

I have only found one instance of triple-backticks code-blocks not having 
been coded correctly.

That's at line 539 in this file,

```
./operations/kubernetes/Troubleshoot_Postgres_Database.md
```
where there's a block closed with a double tick, not a triple.


Some other news:

There's one place where the basic script I have been running to check, for
unclosed triple-backticks running into other Markdown commands, trips up,
and that's because of the use of a double-hash inside a code block, eg

```
## This example assumes the csm-1.0.0 release is currently running and the csm-1.0.0.tar.gz has been pulled down under /root
ncn# cd /root
ncn# tar -xzf csm-1.0.0.tar.gz
```

where the double-hash is the 2nd-level heading markup in Markdown.

FWIW, that's at line 73 in 

```
./operations/CSM_product_management/Post_Install_Customizations.md
```

and it's worth noting that the comment pretty much echoes the text in the
paragraph above the code-block anyway.

Now yes, I could try and write a better parser, but do you (or perhaps: do the docs) need 
to have comments inside the code-blocks anyway?

It doesn't look, given the prompts, as though such code-blocks are meant to
be cut and pasted directly, so do you gain anything from commenting inside
them?

More of an observation though, that one.

**Comment by pawsey-kbuckley** [comment]
Just in case anyone is interested, the "tooling harness" I have been using
to render the sources in Jekyll is now available as a branch stored at my
fork/clone of the vanilla sources

https://github.com/pawsey-kbuckley/docs-csm/tree/format-with-jekyll

As of the main branch's 

commit 0da68dd06d1380b1d343149cdce4ca0eed9e9c6a

it seems rto be rendering, although i can't claim to have viewed every page!

**Comment by rustydb** [comment]
Closing this issue given #1729 and #1728 have merged.
